name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: cockroach version
        required: true
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: docker/login-action@v2.0.0
        with:
          username: hedwigz
          password: ${{ secrets.docker_pass }}

      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: build and push docker
        run: |
          go run main.go ${{ github.event.inputs.version }} > Dockerfile
          docker build -t hedwigz/cockroachdb-single-node:${{ github.event.inputs.version }} .
          docker push hedwigz/cockroachdb-single-node:${{ github.event.inputs.version }}
